# This file is based on the information found in the following links
# https://github.com/pulimento/github-action-hugo-deploy-to-firebase

on: 
  push:
    branches:
      - master
name: Deploy to Hugo to Firebase Hosting on push to master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: pulimento/github-action-hugo-deploy-to-firebase@master
        with:
          firebase-token: ${{ secrets.FIREBASE_TOKEN_MANUALLY_GENERATED }}
