# This file is based on the information found in the following links
# https://github.com/firebase/firebase-tools
# https://github.com/marketplace/actions/hugo-and-firebase 

name: Deploy to Hugo to Firebase Hosting on push to master
'on':
  push:
    branches:
      - master
# jobs:
#   build_and_deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1 
#         with:
#           submodules: true
#       - uses: ryank90/action-hugo-firebase-deploy@master
#         with:
#           #repoToken: '${{ secrets.GITHUB_TOKEN }}'
#           #firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOEGBALLEN_A0916 }}'
#           #channelId: live
#           #projectId: boegballen-a0916
#           firebase-token: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOEGBALLEN_A0916 }}'
#           #firebase-token: ${{ secrets.firebase_token }}
#           #alias: ${{ alias }} // Optional
#           #hugo-params: -D // Optional. Any params for the `hugo` command. [Refer doc here](https://gohugo.io/commands/hugo/) 
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.4.12
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          # The Hugo version to download (if necessary) and use. Example: 0.58.2
          hugo-version: latest # optional, default is latest
          # Download (if necessary) and use Hugo extended version. Example: true
          extended: false # optional, default is false

      - name: Build
        run: hugo

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master  
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BOEGBALLEN_A0916 }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'